source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ParseAuth_Example', :exclusive => true do
  pod 'ParseAuth', :path => '../'
end

target 'ParseAuth_Tests', :exclusive => true do
  pod 'ParseAuth', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
